# Generated by Django 5.1.3 on 2024-11-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=1000)),
                ('dificultad', models.CharField(max_length=200)),
                ('imagen', models.FileField(upload_to='campeones/')),
            ],
        ),
    ]
